# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'sparkly' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sparkly

  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  target 'sparklyTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'GooglePlaces'
    pod 'GoogleMaps'
    pod 'GooglePlacePicker'
    
  end

end
